platform :ios, '11.0'

target 'Todoey (with Realm)' do
  use_frameworks!

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
